artifacts_root: artifacts        # create artifacts folder


data_ingestion:
  root_dir: artifacts/data_ingestion   # create data_ingestion folder inside artifacts folder
  source_URL: https://github.com/adarsh-gowda/cnn_classification/raw/main/Chicken-fecal-images.zip  #dowload from this url
  local_data_file: artifacts/data_ingestion/data.zip  #save url as data.zip
  unzip_dir: artifacts/data_ingestion  #unzip the files inside